version: "3.8"

services:
  # OpenCTI Platform
  opencti:
    image: opencti/opencti:latest
    ports:
      - "8080:8080"  # OpenCTI web interface
    environment:
      # Set your OpenCTI environment variables here (refer to OpenCTI documentation)
      OPENCTI_** : "..."
    volumes:
      - opencti_data:/var/www/opencti  # Persistent storage for OpenCTI data

  # MISP Threat Intelligence Platform
  misp:
    image: gridplane/misp:latest
    ports:
      - "8081:80"  # MISP web interface
    environment:
      # Set your MISP environment variables here (refer to MISP documentation)
      MISP_** : "..."
    volumes:
      - misp_data:/var/www/html  # Persistent storage for MISP data

  # OpenCTI Connector: MITRE ATT&CK
  opencti-connector-mitre:
    image: opencti/connector-mitre:latest
    depends_on:
      - opencti  # Wait for OpenCTI to be ready
    environment:
      # Set your OpenCTI connector environment variables here (refer to OpenCTI documentation)
      OPENCTI_CONNECTOR_MITRE_** : "..."

  # OpenCTI Connector: Greynoise
  opencti-connector-greynoise:
    image: opencti/connector-greynoise:latest
    depends_on:
      - opencti  # Wait for OpenCTI to be ready
    environment:
      # Set your OpenCTI connector environment variables here (refer to OpenCTI documentation)
      OPENCTI_CONNECTOR_GREYNOISE_** : "..."

  # OpenCTI Connector: CVE
  opencti-connector-cve:
    image: opencti/connector-cve:latest
    depends_on:
      - opencti  # Wait for OpenCTI to be ready
    environment:
      # Set your OpenCTI connector environment variables here (refer to OpenCTI documentation)
      OPENCTI_CONNECTOR_CVE_** : "..."

  # OpenCTI Connector: Tor (**Consider security implications before enabling**)
  opencti-connector-tor:
    image: opencti/connector-tor:latest
    depends_on:
      - opencti  # Wait for OpenCTI to be ready
    environment:
      # Set your OpenCTI connector environment variables here (refer to OpenCTI documentation)
      OPENCTI_CONNECTOR_TOR_** : "..."

volumes:
  opencti_data: {}
  misp_data: {}

networks:
  opencti-network: {}  # Shared network for all services
